shell: 
    program: /usr/bin/fish
    args:
        - --command=tmux new-session -A -s main

window:
    dimensions:
        columns: 120
        lines: 80

    padding:
        x: 10
        y: 10

    decorations: full

font:
    normal:
        family: "Dejavu Sans Mono"
        style: Regular

    bold:
        family: "Dejavu Sans Mono"
        style: Medium

    italic:
        family: "Dejavu Sans Mono"
        style: Italic

    size: 18.0
    use_thin_strokes: true

# background_opacity: 0.9

cursor:
    style: Block
    unfocused_hollow: true

# Colors (Snazzy)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#eff0eb'

  # Normal colors
  normal:
    black:   '#282a36'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

  # Bright colors
  bright:
    black:   '#686868'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'
