env:
    TERM: alacritty

window:
    dimensions:
        columns: 130
        lines: 40

    padding:
        x: 10
        y: 10

    decorations: full

font:
    normal:
        family: "Dank Mono"
        style: Regular

    bold:
        family: "Dank Mono"
        style: Bold

    italic:
        family: "Dank Mono"
        style: Italic

    size: 16.0
    use_thin_strokes: true

# background_opacity: 0.9

cursor:
    style: Block
    unfocused_hollow: true

# Colors (Snazzy)
# colors:
#   # Default colors
#   primary:
#     background: '#282a36'
#     foreground: '#eff0eb'

#   # Normal colors
#   normal:
#     black:   '#282a36'
#     red:     '#ff5c57'
#     green:   '#5af78e'
#     yellow:  '#f3f99d'
#     blue:    '#57c7ff'
#     magenta: '#ff6ac1'
#     cyan:    '#9aedfe'
#     white:   '#f1f1f0'

#   # Bright colors
#   bright:
#     black:   '#686868'
#     red:     '#ff5c57'
#     green:   '#5af78e'
#     yellow:  '#f3f99d'
#     blue:    '#57c7ff'
#     magenta: '#ff6ac1'
#     cyan:    '#9aedfe'
#     white:   '#f1f1f0'

# Colors (Material Theme)
# colors:
#   # Default colors
#   primary:
#     background: '0x1e282d'
#     foreground: '0xc4c7d1'

#   # Normal colors
#   normal:
#     black:   '0x666666'
#     red:     '0xeb606b'
#     green:   '0xc3e88d'
#     yellow:  '0xf7eb95'
#     blue:    '0x80cbc4'
#     magenta: '0xff2f90'
#     cyan:    '0xaeddff'
#     white:   '0xffffff'

#   # Bright colors
#   bright:
#     black:   '0xff262b'
#     red:     '0xeb606b'
#     green:   '0xc3e88d'
#     yellow:  '0xf7eb95'
#     blue:    '0x7dc6bf'
#     magenta: '0x6c71c4'
#     cyan:    '0x35434d'
#     white:   '0xffffff'

# KDE Breeze (Ported from Konsole)
# colors:
#   # Default colors
#   primary:
#     background: '0x232627'
#     foreground: '0xfcfcfc'

#     dim_foreground: '0xeff0f1'
#     bright_foreground: '0xffffff'
#     dim_background: '0x31363b'
#     bright_background: '0x000000'

#   # Normal colors
#   normal:
#     black: '0x232627'
#     red: '0xed1515'
#     green: '0x11d116'
#     yellow: '0xf67400'
#     blue: '0x1d99f3'
#     magenta: '0x9b59b6'
#     cyan: '0x1abc9c'
#     white: '0xfcfcfc'

#   # Bright colors
#   bright:
#     black: '0x7f8c8d'
#     red: '0xc0392b'
#     green: '0x1cdc9a'
#     yellow: '0xfdbc4b'
#     blue: '0x3daee9'
#     magenta: '0x8e44ad'
#     cyan: '0x16a085'
#     white: '0xffffff'

#   # Dim colors
#   dim:
#     black: '0x31363b'
#     red: '0x783228'
#     green: '0x17a262'
#     yellow: '0xb65619'
#     blue: '0x1b668f'
#     magenta: '0x614a73'
#     cyan: '0x186c60'
#     white: '0x63686d'

# Colors (Challenger Deep)
colors:
  # Default colors
  primary:
    background: '0x1e1c31'
    foreground: '0xcbe1e7'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xff271d'
    cursor: '0xfbfcfc'
  # Normal colors
  normal:
    black:   '0x141228'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'
  # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'

