env:
  TERM: xterm-256color
  TERM_PROGRAM: alacritty

window:
  dimensions:
    columns: 130
    lines: 40

  padding:
    x: 10
    y: 10

  decorations: full

  option_as_alt: Both

font:
  normal:
    family: "Iosevka Nerd Font"
    style: Regular

  bold:
    family: "Iosevka Nerd Font"
    style: Bold

  italic:
    family: "Iosevka Nerd Font"
    style: Italic

  size: 17

# background_opacity: 0.9
dynamic_title: true

cursor:
  style: Underline

import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#   - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
  # - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
